name: Trigger auto deployment for container-app-uaooztapkhz3e

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-uaooztapkhz3e-AutoDeployTrigger-39bba9d6-5be9-4e02-92ec-6d4385d0a178.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPUAOOZTAPKHZ3E_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPUAOOZTAPKHZ3E_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPUAOOZTAPKHZ3E_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPUAOOZTAPKHZ3E_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPUAOOZTAPKHZ3E_REGISTRY_PASSWORD }}
          containerAppName: container-app-uaooztapkhz3e
          resourceGroup: liamragapplicationdemo8d52
          imageToBuild: default/container-app-uaooztapkhz3e:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


